### ISSUE TITLE
Is it working already?

### ISSUE THREAD

**Issue by vinicius0026** [Chris911/mocha-live-detect#5]
I know this is very early stage in this package's life, but it called my attention since it figured in the last Node Weekly news.
I tried it out, but noting was reported... The code I used to test it is found below.

``` javascript
var request = require('request');
describe('testing http detect', () => {
    it('should detect request', done => {
        request('http://www.google.com', function (err, res, body) {
            done();
        });
    });
});
```

And I run it with `mocha --require mocha-http-detect test.js`.

I'm running node 4.3.2 and mocha 2.4.5. Am I missing something?

**Comment by Chris911** [comment]
@vinicius0026 the package should be functional. Your test is quite similar to one of the [test cases](https://github.com/Chris911/mocha-http-detect/blob/master/test/scenarios/live_requests.js#L9-L15) for this package that should result in the [following output](https://github.com/Chris911/mocha-http-detect/blob/master/test/test.js#L27-L39). 

Let me try to repro locally.

**Comment by Chris911** [comment]
Seems to work over here:
<img width="597" alt="screen shot 2016-04-03 at 1 27 28 pm" src="https://cloud.githubusercontent.com/assets/1198196/14233782/e6811b9c-f99f-11e5-8397-d306cba373eb.png">

**Comment by vinicius0026** [comment]
@Chris911 Thank you for the quick response!

I installed mocha-http-detect locally, but was running as if it was installed globally.

But using the global version of mocha with the local version of mocha-http-detect didn't work.

So:
- Both mocha and mocha-http-detect installed globally, **works**:

```
$ npm install -g mocha mocha-http-detect
$ mocha -r mocha-http-detect test.js
```
- Both mocha and mocha-http-detect installed locally, **works**:

```
$ npm install mocha mocha-http-detect
$ ./node_modules/mocha/bin/mocha -r ./node_modules/mocha-http-detect test.js
```
- Local mocha and global mocha-http-detect, **works**:

```
$ npm install -g mocha-http-detect
$ npm install mocha
$ ./node_modules/mocha/bin/mocha -r mocha-http-detect test.js
```
- Global mocha and local mocha-http-detect, **doesn't work!**

```
$ npm install -g mocha
$ npm install mocha-http-detect
$ mocha -r ./node_modules/mocha-http-detect test.js
```

I don't know if this is an issue that deserves being worked on (this last case), but at least I would change the README to explicitly use the locally installed version of mocha-http-detect (since in the example the module is installed locally).

Thanks again.

**Comment by Chris911** [comment]
Thanks for the feedback. I tested on other modules with mocha and mocha-http-request both installed locally and using `-r mocha-http-detect` (not the full path to node modules) and it worked just fine. Full command was: `./node_modules/.bin/mocha -r mocha-http-detect test.js`.
